name: "Martin Stuurwold - Game Programmer"
description: ""

url: "portfolio.martinstuurwold.com"
email: "&#99;&#111;&#110;&#116;&#97;&#99;&#116;&#64;&#109;&#97;&#114;&#116;&#105;&#110;&#115;&#116;&#117;&#117;&#114;&#119;&#111;&#108;&#100;&#46;&#99;&#111;&#109;"

permalink: pretty

collections:
 projects:
  output: true
  permalink: projects/:path/